// Generated by CoffeeScript 1.4.0
var cmds;

cmds = [afksCommand, allAfksCommand, avgVoteRatioCommand, cookieCommand, dieCommand, disconnectLookupCommand, feedbackCommand, forceSkipCommand, forceWootCommand, helpCommand, lockCommand, mentionCommand, opinionCommand, popCommand, pushCommand, reloadCommand, resetAfkCommand, rodSquadCommand, rulesCommand, skipCommand, sourceCommand, statusCommand, swapCommand, themeCommand, unhookCommand, unlockCommand, voteRatioCommand, welcomeCommand, whyMehCommand, whyWootCommand, wootCommand, zombieCommand];
