// Generated by CoffeeScript 1.4.0
var initEnvironment, initialize, populateUserData, pupOnline;

pupOnline = function() {
  return API.sendChat("/me By the Power of Grayskull... I HAVE THE POWER!!!!!");
};

populateUserData = function() {
  var u, users, _i, _len;
  users = API.getUsers();
  for (_i = 0, _len = users.length; _i < _len; _i++) {
    u = users[_i];
    data.users[u.id] = new User(u);
    data.voteLog[u.id] = {};
  }
};

initEnvironment = function() {
  document.getElementById("woot").click();
  return document.getElementById("chat-sound").click();
};

initialize = function() {
  pupOnline();
  populateUserData();
  initEnvironment();
  initHooks();
  data.startup();
  data.newSong();
  return data.startAfkInterval();
};
