// Generated by CoffeeScript 1.4.0
var roomHelpCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

roomHelpCommand = (function(_super) {

  __extends(roomHelpCommand, _super);

  function roomHelpCommand() {
    return roomHelpCommand.__super__.constructor.apply(this, arguments);
  }

  roomHelpCommand.prototype.init = function() {
    this.command = '.roomhelp';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'user';
  };

  roomHelpCommand.prototype.functionality = function() {
    var msg1;
    msg1 = "Welcome!  ";
    msg1 += "Click the 'Join Waitlist' button and wait your turn to play music. Type '/rules' for specifics.";
    msg1 += "Stay active while waiting to play your song by wooting or you will be removed.";
    return API.sendChat(msg1);
  };

  return roomHelpCommand;

})(Command);
