// Generated by CoffeeScript 1.4.0
var rulesCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

rulesCommand = (function(_super) {

  __extends(rulesCommand, _super);

  function rulesCommand() {
    return rulesCommand.__super__.constructor.apply(this, arguments);
  }

  rulesCommand.prototype.init = function() {
    this.command = '.rules';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'bouncer';
  };

  rulesCommand.prototype.functionality = function() {
    var msg;
    msg = "Room rules: http://tinyurl.com/80sand90s. Basics? Woot while on line and spin anything released 1978-2002 and under 7 minutes";
    return API.sendChat(msg);
  };

  return rulesCommand;

})(Command);
