// Generated by CoffeeScript 1.4.0
var wootCommand,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

wootCommand = (function(_super) {

  __extends(wootCommand, _super);

  function wootCommand() {
    return wootCommand.__super__.constructor.apply(this, arguments);
  }

  wootCommand.prototype.init = function() {
    this.command = '.woot';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'user';
  };

  wootCommand.prototype.functionality = function() {
    var msg, nameIndex;
    msg = "We like active DJs and a positive environment. Please remember			to woot for every song while you are in the DJ line.			We recommend using one of the scripts/extensions			available by clicking the room name on the top of this page.";
    if ((nameIndex = this.msgData.message.indexOf('@')) !== -1) {
      return API.sendChat(this.msgData.message.substr(nameIndex) + ', ' + msg);
    } else {
      return API.sendChat(msg);
    }
  };

  return wootCommand;

})(Command);
